#SQL Database Install and Configure

- name: Install SQL Packages
  apt:
    name:
      - mariadb-server
      - python3-pymysql
    state: latest

- name: Creating Configuration File
  file:
    path: /etc/mysql/mariadb.conf.d/99-openstack.cnf
    state: touch
    owner: root
    group: root
    mode: 0777

- name: Editing The Configuration File
  lineinfile:
        dest: /etc/mysql/mariadb.conf.d/99-openstack.cnf
        line: "{{ item  }}"
        state: present
        backup: yes
  with_items:
        - '[mysqld]'
        - 'bind-address = 10.0.0.11'
        - ' '
        - 'default-storage-engine = innodb'
        - 'innodb_file_per_tabl = on'
        - 'max_connections = 4096'
        - 'collation-server = utf8_general_ci'
        - 'character-ser-server = utf8'

- name: Restart MySQL Service
  service:
    name: mysql
    state: restarted
    enabled: true

- name: Securing database service
  expect:
    command: mysql_secure_installation
    responses:
      'Enter current password for root': ''
      'Set root password': 'n'
      'Remove anonymous users': 'y'
      'Disallow root login remotely': 'y'
      'Remove test database': 'y'
      'Reload privilege tables now': 'y'
    timeout: 1
  register: secure_mariadb
  failed_when: "'... Failed!' in secure_mariadb.stdout_lines"
